name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: speedtesting.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t speedtesting.azurecr.io/tcp-server:latest
        docker push speedtesting.azurecr.io/tcp-server:latest

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'SpeedTesting'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'speedtesting.azurecr.io/tcp-server:latest'
